// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import ChartsController from "./charts_controller"
application.register("charts", ChartsController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import ExerciseSelectController from "./exercise_select_controller"
application.register("exercise-select", ExerciseSelectController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SetsController from "./sets_controller"
application.register("sets", SetsController)