inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # Rubyのバージョン
  TargetRubyVersion: 3.2
  
  SuggestExtensions: false
  # 最新のルールを適用する
  NewCops: enable
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true

  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/**/*"
    - "config/environments/*"
    - "config/initializers/**/*"
    - "config/puma.rb"
    - "public/**/*"
    - "storage/**/*"

### ルールのカスタマイズ

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "config/routes.rb"

Metrics/AbcSize:
  Max: 40

# ブロック内の行数をチェックする
Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"

# 一行あたりの文字数
Layout/LineLength:
  Enabled: false

# --- スタイル調整（視覚的ルール） ---
Layout/MultilineMethodCallIndentation:
  Enabled: false    # インデント誤差は自動整形に任せる
Style/MultilineBlockChain:
  Enabled: false    # map.sort_by など可読性優先で許容


# 日本語にコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスにコメントを残さなくても良い
Style/Documentation:
  Enabled: false

# コントローラ等のモジュールをネストしての宣言
Style/ClassAndModuleChildren:
  Enabled: false

# 文字列のfreeze
Style/FrozenStringLiteralComment:
  Enabled: false

# ガード節の提案
Style/GuardClause:
  Enabled: false

# 文字列のダブルクォートチェック
Style/StringLiterals:
  Enabled: false

# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Enabled: false

# 文字列による配列の%記法のチェック
Style/WordArray:
  Enabled: false

# 変数名に数字を許可
Naming/VariableNumber:
  Enabled: false

# = と == の指摘
Lint/AssignmentInCondition:
  Enabled: false

# メソッド名等の命名の指摘
Naming/PredicatePrefix:
  Enabled: false

# 未i18nのチェック
Rails/I18nLocaleTexts:
  Enabled: false

# before_actionの際の未定義メソッドのチェック
Rails/LexicallyScopedActionFilter:
  Enabled: false

# Rspecでの１つのitブロックの中のexpectの許容数
RSpec/MultipleExpectations:
  Enabled: false

# Rspecでの１つのitブロックの行数の上限
RSpec/ExampleLength:
  Max: 20

# RSpecでのletの数の制限
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# AnyInstance
RSpec/AnyInstance:
  Enabled: false
